<#
.SYNOPSIS
  Creates or updates the ALIDADA Ledger Book TEST server: a separate copy of the
  app with its own address, its own empty database and a "TEST SERVER" banner.
  Nothing it does touches the live server or the live database.

.EXAMPLE
  npm run test-server            # create / update the test server
  npm run test-server:reset      # wipe ALL test data and start again from /setup

  If the test database id cannot be looked up automatically, pass it yourself
  (find it with: npx wrangler d1 list):
  powershell -ExecutionPolicy Bypass -File scripts\test-server.ps1 -DatabaseId <uuid>

  (or: powershell -ExecutionPolicy Bypass -File scripts\test-server.ps1 [-Reset])
#>
param([switch]$Reset, [string]$DatabaseId)

$ErrorActionPreference = 'Continue'
Set-Location (Split-Path -Parent $PSScriptRoot)

$Worker = 'alidada-test'
$Db = 'alidada-ledger-test-db'
$Bucket = 'alidada-ledger-docs-test'
$Cfg = 'wrangler.test.toml'
$SecretsFile = '.test-secrets'

function Say($text) { Write-Host "`n> $text" -ForegroundColor Cyan }
function Fail($text) { Write-Host "`nX $text" -ForegroundColor Red; exit 1 }

# Run wrangler, stop on failure.
function Wr {
  & npx --yes wrangler @args
  if ($LASTEXITCODE -ne 0) { Fail "wrangler $($args -join ' ') failed - see the message above." }
}

$UuidPattern = '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'

# Look the test database up by name. Parsed with a regex rather than
# ConvertFrom-Json so stray banner lines in the output cannot break it.
function Get-DbId {
  $text = (& npx --yes wrangler d1 list --json | ForEach-Object { "$_" }) -join "`n"
  $pattern = '"uuid"\s*:\s*"(' + $UuidPattern + ')"\s*,\s*"name"\s*:\s*"' + [regex]::Escape($Db) + '"'
  $m = [regex]::Match($text, $pattern)
  if ($m.Success) { return $m.Groups[1].Value }
  # Field order is not guaranteed: fall back to scanning object by object.
  foreach ($obj in [regex]::Matches($text, '\{[^{}]*\}')) {
    if ($obj.Value -match ('"name"\s*:\s*"' + [regex]::Escape($Db) + '"') -and $obj.Value -match ('"uuid"\s*:\s*"(' + $UuidPattern + ')"')) {
      return $Matches[1]
    }
  }
  return $null
}

function New-RandomKey([int]$bytes = 24) {
  $buf = New-Object byte[] $bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
  return ([Convert]::ToBase64String($buf) -replace '[+/=]', '')
}

if (-not (Test-Path 'node_modules\wrangler') -and -not (Test-Path 'node_modules/wrangler')) {
  Say 'Installing dependencies (first run only)'
  & npm install --no-audit --no-fund
}

Say 'Checking your Cloudflare sign-in'
Wr whoami

# ---- 1. Test database -------------------------------------------------------
Say "Test database: $Db"
if ($DatabaseId) {
  if ($DatabaseId -notmatch "^$UuidPattern$") { Fail "-DatabaseId must look like 3af9aed2-3e54-4661-971d-e42a723d6eae" }
  $id = $DatabaseId
} else {
  $id = Get-DbId
}
if (-not $id) {
  $out = (& npx --yes wrangler d1 create $Db | ForEach-Object { "$_" })
  $createExit = $LASTEXITCODE
  $out | ForEach-Object { Write-Host $_ }
  # The create output itself contains the new id (database_id = "...").
  $m = [regex]::Match(($out -join "`n"), '"?database_id"?\s*[:=]\s*"(' + $UuidPattern + ')"')
  if ($m.Success) { $id = $m.Groups[1].Value }
  # Otherwise (e.g. it already existed) look it up, allowing a few seconds for
  # a brand-new database to appear in Cloudflare's list.
  for ($try = 1; -not $id -and $try -le 6; $try++) {
    Start-Sleep -Seconds 3
    $id = Get-DbId
  }
  if (-not $id -and $createExit -ne 0) { Fail "Could not create $Db - see the message above." }
}
if (-not $id) {
  Fail "Could not read the id of $Db. Run: npx wrangler d1 list   then re-run this script with  -DatabaseId <the uuid shown for $Db>"
}
Write-Host "  database_id = $id"

# ---- 2. Test document storage (optional) --------------------------------------
Say "Test document storage: $Bucket"
$hasBucket = $false
$buckets = (& npx --yes wrangler r2 bucket list) -join "`n"
if ($LASTEXITCODE -eq 0 -and $buckets -match [regex]::Escape($Bucket)) {
  $hasBucket = $true
} else {
  & npx --yes wrangler r2 bucket create $Bucket
  if ($LASTEXITCODE -eq 0) { $hasBucket = $true }
  else { Write-Host '  R2 is not available - the test server will run without document upload.' -ForegroundColor Yellow }
}

# ---- 3. Generate the test config (git-ignored; the live wrangler.toml is untouched) ----
$compat = '2025-09-01'
$m = Select-String -Path 'wrangler.toml' -Pattern '^compatibility_date = "(.+)"'
if ($m) { $compat = $m.Matches[0].Groups[1].Value }
$toml = @"
# GENERATED by scripts/test-server.ps1 - TEST server only. Do not commit.
name = "$Worker"
main = "src/index.js"
compatibility_date = "$compat"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
html_handling = "none"
not_found_handling = "none"

[vars]
COMPANY_NAME = "ALIDADA Limited (TEST)"
APP_ENV = "test"

[[d1_databases]]
binding = "DB"
database_name = "$Db"
database_id = "$id"
"@
if ($hasBucket) {
  $toml += "`n`n[[r2_buckets]]`nbinding = `"BUCKET`"`nbucket_name = `"$Bucket`""
}
Set-Content -Path $Cfg -Value $toml -Encoding ascii

# ---- 4. Optional reset: wipe every test table ---------------------------------------
if ($Reset) {
  Write-Host "`nThis deletes ALL data on the TEST server ($Db): users, transactions, messages, everything." -ForegroundColor Yellow
  Write-Host 'The live server is not affected.' -ForegroundColor Yellow
  $answer = Read-Host 'Type RESET to continue'
  if ($answer -ne 'RESET') { Fail 'Reset cancelled. Nothing was changed.' }
  $tables = 'users', 'limit_history', 'counters', 'transactions', 'transaction_events', 'notifications', 'tags', 'settings', 'documents', 'audit_log'
  $sqlFile = Join-Path ([System.IO.Path]::GetTempPath()) 'alidada-test-reset.sql'
  Set-Content -Path $sqlFile -Value (($tables | ForEach-Object { "DROP TABLE IF EXISTS $_;" }) -join "`n") -Encoding ascii
  Say 'Wiping test data'
  Wr d1 execute $Db --remote "--file=$sqlFile" --yes -c $Cfg
  Remove-Item $sqlFile -ErrorAction SilentlyContinue
}

# ---- 5. Tables, deploy, secrets ----------------------------------------------------
Say 'Creating tables (safe to repeat)'
Wr d1 execute $Db --remote --file=schema/schema.sql --yes -c $Cfg

Say "Deploying the test server ($Worker)"
Wr deploy -c $Cfg

Say 'Secret keys'
# The secrets can only go onto a Worker that deploy actually created; otherwise
# wrangler would silently create an empty placeholder Worker to hold them.
$existing = (& npx --yes wrangler secret list -c $Cfg | ForEach-Object { "$_" }) -join "`n"
if ($LASTEXITCODE -ne 0) {
  Fail "The test app ($Worker) was not found on Cloudflare, so the deploy step did not complete (network problem?). Run the script again."
}
$saved = @{}
if (Test-Path $SecretsFile) {
  foreach ($line in Get-Content $SecretsFile) {
    $i = $line.IndexOf('=')
    if ($i -gt 0) { $saved[$line.Substring(0, $i)] = $line.Substring($i + 1) }
  }
}
foreach ($name in 'SESSION_SECRET', 'BOOTSTRAP_KEY') {
  if ($existing -match "`"$name`"") { Write-Host "  $name already set - keeping it"; continue }
  if ($name -eq 'BOOTSTRAP_KEY') { $value = 'test-' + (New-RandomKey 6) } else { $value = New-RandomKey 24 }
  # Retry: a brief network drop ("fetch failed") should not stop the run.
  $ok = $false
  for ($try = 1; -not $ok -and $try -le 3; $try++) {
    if ($try -gt 1) { Write-Host "  Retrying $name in 5 seconds (attempt $try of 3)..." -ForegroundColor Yellow; Start-Sleep -Seconds 5 }
    $value | & npx --yes wrangler secret put $name -c $Cfg
    $ok = ($LASTEXITCODE -eq 0)
  }
  if (-not $ok) { Fail "Could not set $name (network problem?). Check your internet connection and run the script again - it will pick up where it left off." }
  $saved[$name] = $value
}
Set-Content -Path $SecretsFile -Value (($saved.Keys | ForEach-Object { "$_=$($saved[$_])" }) -join "`n") -Encoding ascii

Write-Host "`n==================================================================" -ForegroundColor Green
Write-Host ' TEST server is ready.' -ForegroundColor Green
Write-Host " Address:   https://$Worker.<your-subdomain>.workers.dev (shown above)"
if ($saved['BOOTSTRAP_KEY']) {
  Write-Host " Setup key: $($saved['BOOTSTRAP_KEY'])   (use it on the /setup page)"
} else {
  Write-Host ' Setup key: the one you set earlier (not saved on this PC)'
}
Write-Host ' Every page shows an orange TEST SERVER banner. The live server is untouched.'
Write-Host '==================================================================' -ForegroundColor Green
